version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./app:/root/app"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY}
    ports:
      - "8000:8000"